apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: my-voting-app
    tier: postgres
spec:
  containers:
    - image: postgres
      name: postgres:9.4
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name:  POSTGRES_PASSWORD
        value: "postgres"

