apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: my-voting-app
    tier: redis
spec:
  containers:
    - image: redis
      name: redis:latest
    ports:
      - containerPort: 6379

