apiVersion: v1
kind: Pod
metadata:
  name: results-app
  labels:
    app: my-voting-app
    tier: results
spec:
  containers:
    - image: dockersamples/examplevotingapp_result
      name: results-app
      ports:
        - containerPort: 80
