apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    app: my-voting-app
    tier: voting
spec:
  containers:
    - image: dockersamples/examplevotingapp_vote
      name: voting-app
      ports:
        - containerPort: 80
