apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    app: my-voting-app
    tier: worker
spec:
  containers:
    - image: dockersamples/examplevotingapp_worker
      name: worker-app

